package com.zacle.spendtrack.core.designsystem.util

import android.content.Context
import com.zacle.spendtrack.core.shared_resources.R

data class Currency(
    val code: String,
    val name: String,
    val symbol: String,
    val country: String,
    val flagResId: Int
)

fun getCurrencies(context: Context) =
    listOf(
        Currency("AED", context.getString(R.string.AED), "د.إ", context.getString(R.string.AED_country), R.drawable.uae),
        Currency("AFN", context.getString(R.string.AFN), "؋", context.getString(R.string.AFN_country), R.drawable.afghanistan),
        Currency("ALL", context.getString(R.string.ALL), "L", context.getString(R.string.ALL_country), R.drawable.albania),
        Currency("AMD", context.getString(R.string.AMD), "֏", context.getString(R.string.AMD_country), R.drawable.armenia),
        Currency("ANG", context.getString(R.string.ANG), "ƒ", context.getString(R.string.ANG_country), R.drawable.netherlands_antilles),
        Currency("ARS", context.getString(R.string.ARS), "$", context.getString(R.string.ARS_country), R.drawable.argentina),
        Currency("AUD", context.getString(R.string.AUD), "$", context.getString(R.string.AUD_country), R.drawable.australia),
        Currency("AWG", context.getString(R.string.AWG), "ƒ", context.getString(R.string.AWG_country), R.drawable.aruba),
        Currency("AZN", context.getString(R.string.AZN), "₼", context.getString(R.string.AZN_country), R.drawable.azerbaijan),
        Currency("BAM", context.getString(R.string.BAM), "KM", context.getString(R.string.BAM_country), R.drawable.bosnia),
        Currency("BDT", context.getString(R.string.BDT), "৳", context.getString(R.string.BDT_country), R.drawable.bangladesh),
        Currency("BGN", context.getString(R.string.BGN), "лв", context.getString(R.string.BGN_country), R.drawable.bulgaria),
        Currency("BHD", context.getString(R.string.BHD), ".د.ب", context.getString(R.string.BHD_country), R.drawable.bahrain),
        Currency("BND", context.getString(R.string.BND), "$", context.getString(R.string.BND_country), R.drawable.brunei),
        Currency("BOB", context.getString(R.string.BOB), "Bs.", context.getString(R.string.BOB_country), R.drawable.bolivia),
        Currency("BRL", context.getString(R.string.BRL), "R$", context.getString(R.string.BRL_country), R.drawable.brazil),
        Currency("BTN", context.getString(R.string.BTN), "Nu.", context.getString(R.string.BTN_country), R.drawable.bhutan),
        Currency("BWP", context.getString(R.string.BWP), "P", context.getString(R.string.BWP_country), R.drawable.botswana),
        Currency("BYN", context.getString(R.string.BYN), "Br", context.getString(R.string.BYN_country), R.drawable.belarus),
        Currency("BZD", context.getString(R.string.BZD), "$", context.getString(R.string.BZD_country), R.drawable.belize),
        Currency("CAD", context.getString(R.string.CAD), "$", context.getString(R.string.CAD_country), R.drawable.canada),
        Currency("CDF", context.getString(R.string.CDF), "FC", context.getString(R.string.CDF_country), R.drawable.congo),
        Currency("CHF", context.getString(R.string.CHF), "CHF", context.getString(R.string.CHF_country), R.drawable.switzerland),
        Currency("CLP", context.getString(R.string.CLP), "$", context.getString(R.string.CLP_country), R.drawable.chile),
        Currency("CNY", context.getString(R.string.CNY), "¥", context.getString(R.string.CNY_country), R.drawable.china),
        Currency("COP", context.getString(R.string.COP), "$", context.getString(R.string.COP_country), R.drawable.colombia),
        Currency("CRC", context.getString(R.string.CRC), "₡", context.getString(R.string.CRC_country), R.drawable.costa_rica),
        Currency("CVE", context.getString(R.string.CVE), "$", context.getString(R.string.CVE_country), R.drawable.cape_verde),
        Currency("CZK", context.getString(R.string.CZK), "Kč", context.getString(R.string.CZK_country), R.drawable.czech_republic),
        Currency("DJF", context.getString(R.string.DJF), "Fdj", context.getString(R.string.DJF_country), R.drawable.djibouti),
        Currency("DKK", context.getString(R.string.DKK), "kr", context.getString(R.string.DKK_country), R.drawable.denmark),
        Currency("DOP", context.getString(R.string.DOP), "RD$", context.getString(R.string.DOP_country), R.drawable.dominican_republic),
        Currency("DZD", context.getString(R.string.DZD), "د.ج", context.getString(R.string.DZD_country), R.drawable.algeria),
        Currency("EGP", context.getString(R.string.EGP), "£", context.getString(R.string.EGP_country), R.drawable.egypt),
        Currency("ERN", context.getString(R.string.ERN), "Nfk", context.getString(R.string.ERN_country), R.drawable.eritrea),
        Currency("ETB", context.getString(R.string.ETB), "Br", context.getString(R.string.ETB_country), R.drawable.ethiopia),
        Currency("EUR", context.getString(R.string.EUR), "€", context.getString(R.string.EUR_country), R.drawable.europe),
        Currency("FJD", context.getString(R.string.FJD), "$", context.getString(R.string.FJD_country), R.drawable.fiji),
        Currency("FKP", context.getString(R.string.FKP), "£", context.getString(R.string.FKP_country), R.drawable.falkland_islands),
        Currency("GBP", context.getString(R.string.GBP), "£", context.getString(R.string.GBP_country), R.drawable.uk),
        Currency("GEL", context.getString(R.string.GEL), "₾", context.getString(R.string.GEL_country), R.drawable.georgia),
        Currency("GHS", context.getString(R.string.GHS), "₵", context.getString(R.string.GHS_country), R.drawable.ghana),
        Currency("GIP", context.getString(R.string.GIP), "£", context.getString(R.string.GIP_country), R.drawable.gibraltar),
        Currency("GMD", context.getString(R.string.GMD), "D", context.getString(R.string.GMD_country), R.drawable.gambia),
        Currency("GNF", context.getString(R.string.GNF), "FG", context.getString(R.string.GNF_country), R.drawable.guinea),
        Currency("GTQ", context.getString(R.string.GTQ), "Q", context.getString(R.string.GTQ_country), R.drawable.guatemala),
        Currency("GYD", context.getString(R.string.GYD), "$", context.getString(R.string.GYD_country), R.drawable.guyana),
        Currency("HKD", context.getString(R.string.HKD), "$", context.getString(R.string.HKD_country), R.drawable.hong_kong),
        Currency("HNL", context.getString(R.string.HNL), "L", context.getString(R.string.HNL_country), R.drawable.honduras),
        Currency("HRK", context.getString(R.string.HRK), "kn", context.getString(R.string.HRK_country), R.drawable.croatia),
        Currency("HTG", context.getString(R.string.HTG), "G", context.getString(R.string.HTG_country), R.drawable.haiti),
        Currency("HUF", context.getString(R.string.HUF), "Ft", context.getString(R.string.HUF_country), R.drawable.hungary),
        Currency("IDR", context.getString(R.string.IDR), "Rp", context.getString(R.string.IDR_country), R.drawable.indonesia),
        Currency("ILS", context.getString(R.string.ILS), "₪", context.getString(R.string.ILS_country), R.drawable.israel),
        Currency("INR", context.getString(R.string.INR), "₹", context.getString(R.string.INR_country), R.drawable.india),
        Currency("IQD", context.getString(R.string.IQD), "ع.د", context.getString(R.string.IQD_country), R.drawable.iraq),
        Currency("IRR", context.getString(R.string.IRR), "﷼", context.getString(R.string.IRR_country), R.drawable.iran),
        Currency("ISK", context.getString(R.string.ISK), "kr", context.getString(R.string.ISK_country), R.drawable.iceland),
        Currency("JMD", context.getString(R.string.JMD), "$", context.getString(R.string.JMD_country), R.drawable.jamaica),
        Currency("JOD", context.getString(R.string.JOD), "د.ا", context.getString(R.string.JOD_country), R.drawable.jordan),
        Currency("JPY", context.getString(R.string.JPY), "¥", context.getString(R.string.JPY_country), R.drawable.japan),
        Currency("KES", context.getString(R.string.KES), "KSh", context.getString(R.string.KES_country), R.drawable.kenya),
        Currency("KGS", context.getString(R.string.KGS), "лв", context.getString(R.string.KGS_country), R.drawable.kyrgyzstan),
        Currency("KHR", context.getString(R.string.KHR), "៛", context.getString(R.string.KHR_country), R.drawable.cambodia),
        Currency("KRW", context.getString(R.string.KRW), "₩", context.getString(R.string.KRW_country), R.drawable.south_korea),
        Currency("KWD", context.getString(R.string.KWD), "د.ك", context.getString(R.string.KWD_country), R.drawable.kuwait),
        Currency("KYD", context.getString(R.string.KYD), "$", context.getString(R.string.KYD_country), R.drawable.cayman_islands),
        Currency("KZT", context.getString(R.string.KZT), "₸", context.getString(R.string.KZT_country), R.drawable.kazakhstan),
        Currency("LAK", context.getString(R.string.LAK), "₭", context.getString(R.string.LAK_country), R.drawable.laos),
        Currency("LBP", context.getString(R.string.LBP), "ل.ل", context.getString(R.string.LBP_country), R.drawable.lebanon),
        Currency("LKR", context.getString(R.string.LKR), "Rs", context.getString(R.string.LKR_country), R.drawable.sri_lanka),
        Currency("LRD", context.getString(R.string.LRD), "$", context.getString(R.string.LRD_country), R.drawable.liberia),
        Currency("LYD", context.getString(R.string.LYD), "د.ل", context.getString(R.string.LYD_country), R.drawable.libya),
        Currency("MAD", context.getString(R.string.MAD), "د.م.", context.getString(R.string.MAD_country), R.drawable.morocco),
        Currency("MDL", context.getString(R.string.MDL), "L", context.getString(R.string.MDL_country), R.drawable.moldova),
        Currency("MGA", context.getString(R.string.MGA), "Ar", context.getString(R.string.MGA_country), R.drawable.madagascar),
        Currency("MKD", context.getString(R.string.MKD), "ден", context.getString(R.string.MKD_country), R.drawable.north_macedonia),
        Currency("MMK", context.getString(R.string.MMK), "K", context.getString(R.string.MMK_country), R.drawable.myanmar),
        Currency("MNT", context.getString(R.string.MNT), "₮", context.getString(R.string.MNT_country), R.drawable.mongolia),
        Currency("MOP", context.getString(R.string.MOP), "P", context.getString(R.string.MOP_country), R.drawable.macao),
        Currency("MRU", context.getString(R.string.MRU), "UM", context.getString(R.string.MRU_country), R.drawable.mauritania),
        Currency("MUR", context.getString(R.string.MUR), "₨", context.getString(R.string.MUR_country), R.drawable.mauritius),
        Currency("MVR", context.getString(R.string.MVR), "Rf", context.getString(R.string.MVR_country), R.drawable.maldives),
        Currency("MWK", context.getString(R.string.MWK), "MK", context.getString(R.string.MWK_country), R.drawable.malawi),
        Currency("MXN", context.getString(R.string.MXN), "$", context.getString(R.string.MXN_country), R.drawable.mexico),
        Currency("MYR", context.getString(R.string.MYR), "RM", context.getString(R.string.MYR_country), R.drawable.malasya),
        Currency("MZN", context.getString(R.string.MZN), "MT", context.getString(R.string.MZN_country), R.drawable.mozambique),
        Currency("NAD", context.getString(R.string.NAD), "$", context.getString(R.string.NAD_country), R.drawable.namibia),
        Currency("NGN", context.getString(R.string.NGN), "₦", context.getString(R.string.NGN_country), R.drawable.nigeria),
        Currency("NIO", context.getString(R.string.NIO), "C$", context.getString(R.string.NIO_country), R.drawable.nicaragua),
        Currency("NOK", context.getString(R.string.NOK), "kr", context.getString(R.string.NOK_country), R.drawable.norway),
        Currency("NZD", context.getString(R.string.NZD), "$", context.getString(R.string.NZD_country), R.drawable.new_zealand),
        Currency("PEN", context.getString(R.string.PEN), "S/", context.getString(R.string.PEN_country), R.drawable.peru),
        Currency("PGK", context.getString(R.string.PGK), "K", context.getString(R.string.PGK_country), R.drawable.papua_new_guinea),
        Currency("PHP", context.getString(R.string.PHP), "₱", context.getString(R.string.PHP_country), R.drawable.philippines),
        Currency("PKR", context.getString(R.string.PKR), "Rs", context.getString(R.string.PKR_country), R.drawable.pakistan),
        Currency("PLN", context.getString(R.string.PLN), "zł", context.getString(R.string.PLN_country), R.drawable.poland),
        Currency("PYG", context.getString(R.string.PYG), "₲", context.getString(R.string.PYG_country), R.drawable.paraguay),
        Currency("QAR", context.getString(R.string.QAR), "ر.ق", context.getString(R.string.QAR_country), R.drawable.qatar),
        Currency("RON", context.getString(R.string.RON), "lei", context.getString(R.string.RON_country), R.drawable.romania),
        Currency("RSD", context.getString(R.string.RSD), "дин", context.getString(R.string.RSD_country), R.drawable.serbia),
        Currency("RUB", context.getString(R.string.RUB), "₽", context.getString(R.string.RUB_country), R.drawable.russia),
        Currency("RWF", context.getString(R.string.RWF), "FRw", context.getString(R.string.RWF_country), R.drawable.rwanda),
        Currency("SAR", context.getString(R.string.SAR), "ر.س", context.getString(R.string.SAR_country), R.drawable.saudi_arabia),
        Currency("SBD", context.getString(R.string.SBD), "$", context.getString(R.string.SBD_country), R.drawable.solomon_islands),
        Currency("SCR", context.getString(R.string.SCR), "₨", context.getString(R.string.SCR_country), R.drawable.seychelles),
        Currency("SDG", context.getString(R.string.SDG), "ج.س.", context.getString(R.string.SDG_country), R.drawable.sudan),
        Currency("SEK", context.getString(R.string.SEK), "kr", context.getString(R.string.SEK_country), R.drawable.sweden),
        Currency("SGD", context.getString(R.string.SGD), "$", context.getString(R.string.SGD_country), R.drawable.singapore),
        Currency("SLL", context.getString(R.string.SLL), "Le", context.getString(R.string.SLL_country), R.drawable.sierra_leone),
        Currency("SOS", context.getString(R.string.SOS), "S", context.getString(R.string.SOS_country), R.drawable.somalia),
        Currency("SRD", context.getString(R.string.SRD), "$", context.getString(R.string.SRD_country), R.drawable.suriname),
        Currency("SSP", context.getString(R.string.SSP), "£", context.getString(R.string.SSP_country), R.drawable.south_sudan),
        Currency("STN", context.getString(R.string.STN), "Db", context.getString(R.string.STN_country), R.drawable.sao_tome_and_principe),
        Currency("SYP", context.getString(R.string.SYP), "ل.س", context.getString(R.string.SYP_country), R.drawable.syria),
        Currency("SZL", context.getString(R.string.SZL), "E", context.getString(R.string.SZL_country), R.drawable.swaziland),
        Currency("THB", context.getString(R.string.THB), "฿", context.getString(R.string.THB_country), R.drawable.thailand),
        Currency("TJS", context.getString(R.string.TJS), "SM", context.getString(R.string.TJS_country), R.drawable.tajikistan),
        Currency("TMT", context.getString(R.string.TMT), "m", context.getString(R.string.TMT_country), R.drawable.turkmenistan),
        Currency("TND", context.getString(R.string.TND), "د.ت", context.getString(R.string.TND_country), R.drawable.tunisia),
        Currency("TOP", context.getString(R.string.TOP), "T$", context.getString(R.string.TOP_country), R.drawable.tonga),
        Currency("TRY", context.getString(R.string.TRY), "₺", context.getString(R.string.TRY_country), R.drawable.turkey),
        Currency("TTD", context.getString(R.string.TTD), "$", context.getString(R.string.TTD_country), R.drawable.trinidad_and_tobago),
        Currency("TWD", context.getString(R.string.TWD), "NT$", context.getString(R.string.TWD_country), R.drawable.taiwan),
        Currency("TZS", context.getString(R.string.TZS), "TSh", context.getString(R.string.TZS_country), R.drawable.tanzania),
        Currency("UAH", context.getString(R.string.UAH), "₴", context.getString(R.string.UAH_country), R.drawable.ukraine),
        Currency("UGX", context.getString(R.string.UGX), "USh", context.getString(R.string.UGX_country), R.drawable.uganda),
        Currency("USD", context.getString(R.string.USD), "$", context.getString(R.string.USD_country), R.drawable.usa),
        Currency("UYU", context.getString(R.string.UYU), "\$U", context.getString(R.string.UYU_country), R.drawable.uruguay),
        Currency("UZS", context.getString(R.string.UZS), "сум", context.getString(R.string.UZS_country), R.drawable.uzbekistn),
        Currency("VEF", context.getString(R.string.VEF), "Bs.F", context.getString(R.string.VEF_country), R.drawable.venezuela),
        Currency("VND", context.getString(R.string.VND), "₫", context.getString(R.string.VND_country), R.drawable.vietnam),
        Currency("VUV", context.getString(R.string.VUV), "Vt", context.getString(R.string.VUV_country), R.drawable.vanuatu),
        Currency("WST", context.getString(R.string.WST), "WS$", context.getString(R.string.WST_country), R.drawable.samoa),
        Currency("XAF", context.getString(R.string.XAF), "FCFA", context.getString(R.string.XAF_country), R.drawable.central_african_republic),
        Currency("XOF", context.getString(R.string.XOF), "CFA", context.getString(R.string.XOF_country), R.drawable.west_africa),
        Currency("YER", context.getString(R.string.YER), "ر.ي", context.getString(R.string.YER_country), R.drawable.yemen),
        Currency("ZAR", context.getString(R.string.ZAR), "R", context.getString(R.string.ZAR_country), R.drawable.south_africa),
        Currency("ZMW", context.getString(R.string.ZMW), "ZK", context.getString(R.string.ZMW_country), R.drawable.zambia),
    )

